language: cpp
sudo: required
os: osx
osx_image: xcode7.3
cache: ccache

cache:
  directories:
  - /usr/local

before_install:
  - brew update
  - brew tap homebrew/science
  - brew install ccache
  - brew install octave

script:
  - make check-octave
  - ./success.sh
